Event_dict = {
    "join": "参加時",
    "leave": "退出時"
}
Stat_dict = {
    "members": "メンバー数",
    "humans": "ユーザー数",
    "bots": "ボット数",
    "onlines": "オンライン数",
    "online_per": "オンライン割合",
    "channels": "チャンネル",
    "text_channels": "テキストチャンネル",
    "voice_channels": "ボイスチャンネル",
    "roles": "ロール"
}
en = ""
for ek, ev in Event_dict.items():
    en += f"{ek} - {ev}\n"
st = ""
for ek, ev in Stat_dict.items():
    st += f"{ek} - {ev}\n"
JA_TEXTS = {  # noqa
    "help_title": "ヘルプ",
    "too_high": "値が大きすぎます。",
    "help_closed": "{}でヘルプを再表示",
    "premium": "このコマンドはSevenBot Premium限定です。",
    "premium_desc": "公式サーバーをブーストすると使えるようになります。",
    "serverinfo": {
        "channels": ["チャンネル", "カテゴリー", "テキストチャンネル", "ボイスチャンネル"],
        "members": ["メンバー数", "{0}人\n（{3}ユーザー{1}人 / {4}Bot{2}人）"],
        "owner": "オーナー",
        "emoji": ["絵文字", "通常:{0}個/{2}個\nアニメーション:{1}個/{2}個"],
        "unknown": "サーバーが見付かりません。",
        "noperm": "実行者は取得したいサーバーに入っていません。",
        "created_at": "作成日時"
    },
    "reencode": "文字化け",
    "get_rm": "`@{}`を持っている人",
    "get_rm_more": "他`{}`人…",
    "suggest": "もしかして：",
    "mod_only": "このコマンドはBotオーナーまたはモデレーターにしか実行できません。",
    "cooldown": "このコマンドはクールダウン中です。",
    "cooldown_desc": "`{}`秒後に実行してください。",
    "prefix_changed": "プレフィックスを変更しました。",
    "current": "現在",
    "djs_docs": "", "djs_title": "discord.js 属性検索",
    "djs_more": "他`{}`個…",
    "djs_classes": "クラス",
    "djs_methods": "メソッド",
    "djs_fail": "何も見つかりませんでした。",
    "djs_props": "プロパティ",
    "ltrans": "25ヶ国語再翻訳",
    "dpy_docs": "https://discordpy.readthedocs.io/ja/latest/",
    "dpy_fail": "何も見付かりませんでした。",
    "dpy_title": "discord.py 属性検索",
    "dpy_more": "他`{}`個...",
    "dpy_classes": "クラス",
    "dpy_props": "プロパティ",
    "dpy_methods": "メソッド",
    "clear_format": "引数は`引数=値`の形式で入力して下さい。",
    "clear_keys": "不明な引数({})です。",
    "ot_title": "オセロ",
    "ot_desc": "`11`のように左から、上から何マス目に置くか入力して下さい。",
    "ot_range": "1..8で指定して下さい。",
    "ot_placed": "既に置かれています。",
    "ox_title": "○×ゲーム",
    "ox_bot": "Botはプレイできません。",
    "ox_self": "一人二役はできません。",
    "ox_connection_timeout": "接続がタイムアウトしました。",
    "ox_timeout": "処理がタイムアウトしました。",
    "ox_user_timeout": "操作がタイムアウトしました。",
    "ox_prepare": "準備中…",
    "ox_turn": "{}のターン",
    "ox_win": "{}が勝利しました。",
    "ox_draw": "引き分けです。",
    "short_ok": "短縮が完了しました。",
    "tts_vc_none": "ボイスチャンネルに接続していません。",
    "tts_vc_none_desc": "ボイスチャンネルに接続したあとにこのコマンドを実行して下さい。",
    "tts_joined": "`{}`に接続しました。",
    "tts_dc": "切断しました。",
    "tts_dc_none": "切断するボイスチャンネルがありません。",
    "tts_premium": "SevenBot Premium!",
    "tts_premium_desc": "音声は8倍の音質（512kbps）で再生されます。",
    "tts_voice_changed": "声の種類は{}に設定されました。",
    "tts_voice_fail": "無効な声の種類です。",
    "tts_voice_fail_premium": "abcd以外を指定するにはPremiumに入る必要があります。",
    "tts_speed_range": "声の速度は50～400で指定して下さい。",
    "tts_speed_changed": "声の速度は{}%になりました。",
    "tts_dicts_add": "カスタム辞書に新しい単語を追加しました。",
    "tts_dicts_add_desc": "戻すには`sb#autoreply remove {}`または`sb#autoreply remove {}`を使用してください",
    "tts_dicts_rem_fail": "カスタム辞書に`{}`は含まれていません。",
    "tts_dicts_rem_fail_desc": "`sb#tts dicts list`で確認してください。",
    "tts_dicts_rem_success": "`{}`個の単語を消去しました。",
    "tts_dicts_list": "カスタム辞書一覧",
    "mention_txt": "このサーバーでのプレフィックスは`{}`です。\nメンションでも反応します。",
    "expand_message_fail": "取得に失敗しました。",
    "expand_message_footer": "チャンネル： {}",
    "expand_message_footer2": " • {}個の埋め込み",
    "expand_message_footer3": "サーバー： {} • ",
    "ar_remove_title": "自動返信をオフにする方法",
    "ar_remove_desc": "1. `sb#autoreply list`で削除したい返信のIDを確認\n2. `sb#autoreply remove <ID>`で削除",
    "ar_remove_footer": "この埋め込みは10秒後に消去されます。",
    "ar_list": "自動返信一覧",
    "ar_list_row": ["ID", "条件", "返信"],
    "ar_list_no": "登録されていません。",
    "ar_list_br": "[改行]",
    "ar_list_no_desc": "`sb#autoreply add`で登録してください。",
    "message_delete": "このメッセージは{}秒後に消去されます。",
    "page": "ページ",
    "timeout": "タイムアウトしました。",
    "snowflake": [
        "Snowflakeの情報",
        "作成日時：{0}\n内部WorkerID：{1}\n内部プロセスID：{2}\n番号：{3}"
    ],
    "translate_title": "翻訳（{}から{}へ）",
    "yt_played": "を再生しました。",
    "yt_queued": "をキューに追加しました。",
    "yt_queued_footer": "キューには{}個の曲が入っています。",
    "yt_queue_end": "キューが終了しました。",
    "yt_queue_list": "現在のキュー",
    "yt_queue_empty": "キューは空です。",
    "yt_not_connect": "ボイスチャンネルに接続していません。",
    "yt_not_connect3": "あなたはボイスチャンネルに接続していません。",
    "yt_not_connect2": "接続してから実行してください。",
    "yt_disconnect": "`{}`から切断しました。",
    "yt_reconnect": "`sb#music join`で再接続",
    "bump_detected": "Bumpを検知しました。",
    "bump_detected_desc": "2時間後に通知します。\n`sb#bump deactivate`で無効化します。",
    "bump_alert": "Bumpの時間です！",
    "bump_alert_desc": "`!d bump`で表示順をアップします。",
    "bump_role_set": "Bump通知メンションロールを設定しました。",
    "bump_role_set_none": "Bump通知メンションロールを消去しました。",
    "dissoku_detected": "アップを検知しました。",
    "dissoku_detected_desc": "1時間後に通知します。\n`sb#dissoku deactivate`で無効化します。",
    "dissoku_alert": "アップの時間です！",
    "dissoku_alert_desc": "`/dissoku up`で表示順を上にします。",
    "dissoku_role_set": "アップ通知メンションロールを設定しました。",
    "dissoku_role_set_none": "アップ通知メンションロールを消去しました。",
    "warn": "{}を{}回Warnしました。",
    "warn_desc_info": "{}は{}回Warnされています。",
    "warn_desc_now": "{}回Warnされたため、{}されます。",
    "warn_desc_next": "次の処罰：{} ({}回)",
    "warn_desc_next_none": "次の処罰：なし",
    "warn_punish": {
        "mute": "ミュート",
        "kick": "キック",
        "ban": "BAN",
        "role_add": "ロール追加",
        "role_remove": "ロール剥奪",
    },
    "warn_reason": "Warn",
    "warn_punish_title": "処罰一覧",
    "warn_punish_header": ["回数", "処罰", "詳細"],
    "ws_list": "処罰一覧",
    "ws_list_row": ["回数", "動作"],
    "ws_list_no": "登録されていません。",
    "ws_list_br": "[改行]",
    "ws_list_no_desc": "`sb#warn_settings add`で登録してください。",
    "img_auth_header": "SevenBot 画像認証",
    "archive_title": "このチャンネルをアーカイブしました。",
    "archive_category": "アーカイブ",
    "img_auth_desc": "下のコードを送信してください。",
    "img_auth_warn": "30秒でタイムアウトします。",
    "img_auth_ok": "認証しました。",
    "web_auth": "以下のURLにアクセスしてください。",
    "web_auth_notdm": "DMを送信できなかったため、このチャンネルに送信しました。\n以下のURLにアクセスしてください。",
    "dm_fail": "DMを送信できませんでした。",
    "color_names": ["赤", "オレンジ", "黄緑", "緑", "青緑", "水色", "青", "紺色", "紫", "赤紫"],
    "tts_join": "{}がボイスチャンネルに入室しました。現在、{}人がボイスチャンネルに入っています。",
    "tts_left": "{}がボイスチャンネルから退出しました。現在、{}人がボイスチャンネルに入っています。",
    "activate": "{}を有効にしました。",
    "activate_fail": "既に有効です。",
    "activate_desc": "無効にするには`{}`を使用してください。",
    "deactivate": "{}を無効にしました。",
    "deactivate_fail": "既に無効です。",
    "deactivate_desc": "有効にするには`{}`を使用してください。",
    "voting": ["投票", "タイトル", "複数投票", ["可", "不可"], "選択肢", "終了時刻："],
    "vote_error": ["選択肢が多すぎます。", "選択肢は10個以下にしてください。"],
    "getid_self": ["あなたのIDは`{}`です。", "ご自由にお使いください。"],
    "getid_search": ["`{}`に当てはまったユーザー一覧", "完全一致", "部分一致", "見付かりませんでした。"],
    "ping_title": "Ping測定",
    "ping_desc": "SevenBotのPingは`{}ms`です。",
    "how_to_use": "使用法",
    "getting": "取得中…",
    "favorite": "お気に入り",
    "wait": "しばらくお待ちください。",
    "command_search": "コマンド検索",
    "selected": "が選択されました。",
    "canceled": "キャンセルされました。",
    "nico_failed": "失敗しました。",
    "nico_api_die": "ニコニコのAPIがダウンしています。",
    "nico_wrong_query": "検索語句を変えてやり直してください。",
    "yt_search_result": "検索結果",
    "yt_no_matches": "見付かりませんでした。",
    "yt_premium": "SevenBot Premium!",
    "yt_premium_desc": "音楽は8倍の音質（512kbps）で再生されます。",
    "yt_volume_range": "音量は0～200で指定して下さい。",
    "yt_volume": "音量を変更しました。",
    "yt_volume_desc": "次の曲から適用されます。",
    "yt_volume_now": "現在の音量は{}%です。",
    "yt_search_try_again": "検索語句を変えてやり直してください。",
    "yt_no_fav": "お気に入りが登録されていません。",
    "yt_no_fav_desc": "再生時に{}で登録できます。",
    "yt_play_wait": "再生中...",
    "yt_join_wait": "`{}`に接続中...",
    "yt_join_done": "`{}`に接続しました。",
    "yt_join_desc": "`sb#music`で再生関連のコマンドを表示します。",
    "no_desc": "- 説明なし -",
    "afk_title": "`{}`は現在AFKです。",
    "afk_reason_none": "（理由なし）",
    "afk_reason": "理由：",
    "afk_register": "AFKになりました。",
    "afk_register_desc": "何か発言した瞬間、AFKは解除されます。",
    "afk_off": "AFKが解除されました。",
    "afk_off_desc": "{}件のメンションがありました。",
    "afk_off_unknown": "（不明）",
    "yt_loop_activate": "ループが有効になりました。",
    "yt_loop_deactivate": "ループが無効になりました。",
    "yt_loop_activate_desc": "最後の曲が終了したときに最初から再生します。",
    "yt_loop_deactivate_desc": "最後の曲が終了したらそのまま終了します。",
    "yt_pause_activate": "ポーズしました。",
    "yt_pause_deactivate": "再開しました。",
    "yt_pause_desc": "`sb#music pause`で切り換えます。",
    "yt_stop": "停止しました。",
    "yt_queue_del": "曲を削除しました。",
    "yt_queue_del_desc": "現在キューには{}個の曲が入っています。",
    "yt_queue_del_fail": "曲を削除できませんでした。",
    "yt_queue_del_fail_desc": "番号が不正です。",
    "yt_fail_get": "曲の情報を取得できませんでした。",
    "yt_fail_get_desc": "URLを確認してください。",
    "yt_current_song": "現在の曲",
    "yt_cu": "曲を再生していません。",
    "yt_fav_add": "`{}`をお気に入りに追加しました。",
    "yt_fav_del": "`{}`をお気に入りから除外しました。",
    "yt_fav_info": "お気に入りには{}個の曲が入っています。",
    "yt_not_playing": "曲を再生していません。",
    "yt_now_playing": ["タイトル", "投稿者", "URL", "再生状況"],
    "yt_skip": "スキップしました。",
    "no_role_perm": "`@{}`をつける権限がありません。",
    "yt_queue_end_desc": "`sb#music play`などで登録してください。",
    "yt_footer": "キュー：{}/{} 形式：{}",
    "unknown_cmd": "不明なコマンドです。",
    "rc_title": "ロールの人数一覧",
    "rc_people": "人",
    "see_help": "`sb#help`で確認してください。",
    "bad_arg": "引数が不正です。",
    "error": "エラーが発生しました。",
    "permission_title": "{}の権限一覧",
    "permission_title_channel": "{}の`{}`での権限一覧",
    "permission_value": "権限値：",
    "ls": {
        "not_active": "レベルシステムが無効です。",
        "not_active_desc2": "レベルシステムが有効なサーバーで実行してください。",
        "not_active_desc": "`sb#level_settings activate`で有効化してください。",
        "rank": ["順位", "メンバー名", "レベル", "XP"],
        "rank_title": "レベルランキング",
        "manage": {
            "add": "{}に{}XPを付与しました。",
            "remove": "{}から{}XPを剥奪しました。",
            "reset": "レベルをリセットしました。"
        },
        "roles": {
            "add": "報酬ロールを設定しました。",
            "remove": "報酬ロールを消去しました。",
            "remove_fail": "報酬ロールが見付かりませんでした。",
            "list": "報酬ロール一覧"
        },
        "boost": {
            "add": "レベルブーストを設定しました。",
            "remove": "レベルブーストを消去しました。",
            "remove_fail": "レベルブーストが見付かりませんでした。",
            "list": "レベルブースト一覧"
        }

    },
    "fatal_role_add": "{}人中、{}人にロールを追加しました。（{}人に追加できませんでした。）",
    "fatal_role_remove": "{}人中、{}人からロールを削除しました。（{}人から削除できませんでした。）",
    "fatal_role_kick": "{}人中、{}人をキックしました。（{}人をキックできませんでした。）",
    "fatal_role_dm": "{}人中、{}人にDMを送信しました。（{}人に送信できませんでした。）",
    "fatal_role_dm_title": "`{}`より：",
    "lockdown_title": "このチャンネルを封鎖しました。",
    "lockdown_desc": "以下のロールから`メッセージを送信`権限を剥奪しました。",
    "lockdown_footer": "このメッセージのピン留めを解除しないでください。",
    "unlock_title": "このチャンネルを解放しました。",
    "unlock_desc": "以下のロールに`メッセージを送信`権限を付与しました。",
    "norton_res": "結果は`{}`です。",
    "norton_desc": [["未評価", "まだ評価されていません。"], ["安全", "ノートン セーフウェブが {} を分析して安全性とセキュリティの問題を調べました。 "], ['注意', "［注意］の評価を受けた Web サイトは少数の脅威または迷惑を伴いますが、赤色の［警告］に相当するほど危険とは見なされません。サイトにアクセスする場合には注意が必要です。"], ["警告", "これは既知の危険な Web ページです。このページを表示しないことを推奨します。"]],
    "trans_before": "原文",
    "trans_after": "翻訳後",
    "no_attachments": "添付ファイルがありません。",
    "disabled": "このコマンドは現在無効化されています。",
    "free_channel_title": "フリーチャンネル",
    "free_channel_desc": "下の{}を押してフリーチャンネルを作成",
    "free_channel_ask": "チャンネル名を入力してください。",
    "free_channel_success": "チャンネルを作成しました。",
    "free_channel_success_desc": "チャンネルに移動: {}",
    "free_channel_topic": "{}のフリーチャンネルです。",
    "afk_api": "あなたのAPIキーは`!key`です。\nhttps://api.sevenbot.jp/afk にPOSTリクエストを以下のように送信してください。\n```bash\ncurl -XPUT -H 'authorization:!userid !key' -H \"Content-type: application/json\" -d '{\"reason\":\"Optional\"}' 'https://api.sevenbot.jp/afk'\n```\n詳細は https://sevenbot.jp/api を参照して下さい。",
    "afk_twitter": "このURLで認証を済ませた後、PINをここに送信して下さい。",
    "afk_twitter_fail": "認証に失敗しました。",
    "afk_twitter_success": "`@{}` として認証しました。",
    "afk_twitter_off": "Twitter連携を無効化しました。",
    "afk_twitter_content": "!userはAFKになりました。\n理由：\n!reason\n\nPowered by #SevenBot - https://sevenbot.jp",
    "afk_twitter_content2": "!userのAFKは解除されました。\n\nPowered by #SevenBot - https://sevenbot.jp",
    "lookup": ["{}の情報", "ニックネーム", "ユーザー名", "アカウント作成日時", "サーバー参加日時", ["不明", "オンライン", "退席中", "取り込み中", "オフライン", "ステータス"], "ロール", "Warn回数", "{}回", "このサーバーにはいません。", ["はい", "いいえ"], "見付かりませんでした。", "(API経由)"],
    "abouts": ["SevenBotについて", "開発者", "言語", "公式サーバー（GBan申請などもこちらから）", "サーバー数", "ユーザー数", "グローバルチャット数", "SevenNet数", "top.ggでの高評価数", "{}(今月に{}個)\n高評価は[こちら](https://top.gg/bot/718760319207473152)", "ソースコード", "招待リンク", "サポートサーバー", "スペシャルサンクス（敬称略）",
               "開発支援：[Discord Bot Portal JP](https://discord.gg/FWw6VqQ), [discord.py](https://discord.gg/nXzj3dg), [pythonjp](https://discord.gg/M5NdnCV), [Discord Developers](https://discord.gg/developers)\nサーバー提供：[CyberRex](https://twitter.com/0xerrebyc)", "サーバー", "人"],
    "tree": "このサーバーのチャンネル",
    "ch": {
        "slowmode": ["低速モードは`{}`秒に設定されました。"]
    },
    "big-number": {
        "title": "ビッグナンバー",
        "waiting": "プレイヤーを待っています。",
        "waiting_desc": "ゲームを開始するには`3`人必要です。\n{}で参加（開始）、{}で退出（キャンセル）",
                        "players": "プレイヤー(現在`{}`人)",
                        # "ready": "参加者確定",
                        "cancel": "キャンセル",
                        "ready": "締め切り",
                        "ready_desc": "この`{}`人でゲームを開始します。",
                        "input": "入力",
                        "input_desc": "1~10の整数を入力してください。\n一番数が大きい人が優勝です。\nただし、同じ数字の人がいた場合無効になります。\nそして、1は10にだけ勝てます。\n1分以内に送信してください。",
                        "input2": "受付",
                        "input2_desc": "プレイヤーの入力を待っています。",
                        "input_received": "入力を受け付けました。",
                        "input_received2": "{}の入力を受け付けました。",
                        "no_dm": "DMを送信できませんでした。",
                        "timeout": "入力がありませんでした。",
                        "result": "最終結果",
                        "result_desc1": "{}が`{}`で勝利しました！\nおめでとう！\n**みんなの数字:**\n",
                        "result_desc2": "みんな重複しました！\n引き分け！残念！\n**みんなの数字:**\n",
                        "double": "(重複)"
    },
    "sb#_changed": [
        "sb#は`{}`から`{}`に変更されました。",
        "戻すには`{}change_sb#`だけを実行して下さい。",
        "(デフォルト)"
    ],
    "parse": [
        ["カッコは正常です。", "全ての`(`,`{`,`[`は正常に閉じられています。"],
        "カッコが不正です。",
        "{1}個の`{0}`が閉じられていません。",
        "{1}個の`{0}`が不正な場所にあります。",
        "`{}`が終了していません。"
    ],
    "change_lang": [
        ["言語を変更できませんでした。", "不明な言語（{}）です。"],
        ["言語を変更しました。", "このサーバーの言語は`{}`です。"]
    ],
    "ww": {
        "title": "人狼",
        "role_type": "タイプには`alive`または`dead`を指定してください。",
        "role_set": "{}時のロールは{}に設定されました。",
        "role_set_none": "{}時のロールはなくなりました。",
        "role_alive": "生存",
        "role_dead": "死亡",
        "waiting": "プレイヤーを待っています。",
        "waiting_desc": "ゲームを開始するには`6`人必要です。\n{}で参加（開始）、{}で退出（キャンセル）",
        "players": "プレイヤー(現在`{}`人)",
        # "ready": "参加者確定",
        "cancel": "キャンセル",
        "ready": "締め切り",
        "ready_desc": "この`{}`人でゲームを開始します。",
        "your_role": "あなたは`{}`です。",
        "info": "役職",
                "roles": [
                        ["市民", "能力は何もありません。", 0],
                        ["占い師", "毎晩、誰か1人を選び、その人が_人狼_か_人間_か知ることが出来ます。", 0],
                        ["霊媒師", "昨晩処刑された人が_人狼_か_人間_か知ることが出来ます。", 0],
                        ["狩人", "毎晩、誰か1人を選び、その人を_人狼_から守ることが出来ます。\nただし、昨晩守った人、自分は選ぶことができません。", 0],
                        ["人狼", "毎晩、誰か1人を選び、その人を襲撃します。", 1]
                ],
        "win_cond": ["**勝利条件：**", "_人狼_を全員処刑する。", "人狼の数と人間の数が同数になる。"],
        "team": ["人間", "人狼"],
        "day": "`{}`日目",
        "noon": "昼時間",
                "noon_desc": "昼時間です。「誰が人狼か」を議論して下さい。\n3分後に投票に入ります。\n{}を全員が押すことでスキップできます。\n{}で役職一覧を送信します。\n**現在の生存者：**\n{}",
                "vote": "投票時間",
                "vote2": "投票",
                "vote3": "再投票",
                "vote_desc": "投票です。\n処刑する人の番号を送信して下さい。",
                "vote_wait_desc": "プレイヤーの入力を待っています。",
                "vote_received": "入力を受け付けました。",
                "vote_received2": "__{}__の入力を受け付けました。",
                "vote_draw": "同数票があったため、再投票を行います。",
                "vote_draw2": "再投票しても同数票があったため、くじで__{}__が処刑されました。",
                "vote_result": "処刑",
                "vote_result_dm": "あなたは処刑されました。",
                "vote_result_desc": "__{}__が処刑されました。",
                "remain": "残り {} 人",
                "night": "夜時間",
                "night_desc": "夜時間です。",
                "no_dm": "DMを送信できませんでした。",
                "died": "死亡",
                "died_desc": "__{}__が無残な姿で発見されました。",
                "died_dm": "あなたは死亡しました。",
                "died_fail": "誰も死亡しませんでした。",
                "dead": "(死亡)",
                "result": "ゲーム終了",
                "result_desc1": "村人陣営が勝利しました！\n**役職:**\n{}",
                "result_desc2": "人狼陣営が勝利しました！\n**役職:**\n{}",
                "night_txt": [
                        ["市民", "夜時間には何も出来ません。\nおやすみなさい。", 0],
                        ["占い師", "1人選んでください。\nその人が_人狼_か_人間_か知ることが出来ます。",
                            0, "__{}__は_{}_です。"],
                        ["霊媒師", "1日目なので何も出来ません。", 0, "昨晩処刑された人は_{}_です。"],
                        ["狩人", "1人選んでください。\nその人を_人狼_の襲撃から保護します。", 0],
                        ["人狼", "1人選んでください。\nその人を襲撃します。", 1]
                ]
    },
    "help_move": "移動したいページを送信してください。",
    "not_nsfw": "このコマンドはNSFWチャンネル限定です。",
    "subcommand": "`{}`のサブコマンド",
    "vote_rank": ["順位", "ユーザー名", "Upvote数"],
    "vote_rank_title": "今月のUpvote数ランキング",
    "help_ad": ["`{}`の広告", "この広告にアクセス"],
    "delta_txt": ["日", "時間", "分", "秒", "間"],
    "help_hidden": "このコマンドは非公開です。",
    "help_datail_aliases": "エイリアス",
    "help_datail_count": ["使用回数", "{}回（セーブデータの容量を減らすため、サブコマンドの場合は親コマンドの回数が表示されます。）"],
    "help_datail_subcommands": "サブコマンド",
    "help_datail_aliases_none": "なし",
    "help_datail_subcommands_none": "なし",
    "help_none": "コマンドが見付かりませんでした。",
    "help_datail_none": "説明が見付かりませんでした。",
    "help_datail_syntax_name": "構文",
    "help_datail_category": "カテゴリー",
    "help_datail": {
        "afk": "AFKになります。\nAFK中は、メンション時にAFKであることを伝えます。（もし理由が指定されていれば、理由も伝えます。）\n理由: AFKの理由（文字列、省略で理由なし）",
        "afk key": "AFKのAPIキーを取得します。",
        "afk twitter": "AFKのTwitter連携を設定します。",
        "afk twitter deactivate": "AFKのTwitter連携を解除します。",
        "follow": "お知らせをフォローします。",
        "follow announce": "大きなお知らせをフォローします。",
        "follow updates": "更新ログをフォローします。",
        "level_ranking": "レベルのランキングを表示します。",
        "clear_channel": "チャンネルの履歴を消去します。\nフィルター: 削除したいメッセージのフィルタ（=指定、省略で全て）\n**フィルタ一覧:**\n`user` - 送信元（ユーザー、`u`|`from`）\n`limit` - メッセージの個数（数値、`c`|`count`）\n`length` - メッセージの送信時間（日時、`len`）",
        "tic_tac_toe": "○×ゲームをします。\nターゲット: 対戦相手（メンバー）",
        "get_role_member": "指定したロールを持っている人を表示します。\nロール: メンバーを表示したいロール（ロール）",
        "werewolf": "人狼をします。",
        "sgc": "スーパーグローバルチャットの情報を表示します。",
        "bignum": "ビッグナンバーとかいう謎のゲームをします。",
        "image": "画像関連のコマンドです。",
        "image github": "GitHubのデフォルト風アイコンを生成します。\nシード: 生成する画像のシード（文字列、省略でユーザーID）",
        "image ps4": "PS4のパッケージ風の画像を添付画像から作成します。",
        "image switch": "Switchのパッケージ風の画像を添付画像から作成します。",
        "image neko": "[NekoBot API](https://docs.nekobot.xyz)を使って猫耳っ娘の画像を表示します。",
        "image kemomimi": "[NekoBot API](https://docs.nekobot.xyz)を使ってケモミミっ娘の画像を表示します。",
        "image httpcat": "[httpcat](https://http.cat)の画像を表示します。\nステータスコード: 表示する猫のコード（数値）",
        "image food": "[NekoBot API](https://docs.nekobot.xyz)を使って食べ物の画像を表示します。",
        "tips": "SevenBotのTipsを表示します。\nID: 表示したいTipsのID（文字列、省略でランダム）",
        "tts": "読み上げ関連のコマンドです。\n**読み上げ機能について**\n`sb#tts join`で接続した後、joinを打ったチャンネルでVCに入っている人が発言するとその文章を読み上げます（最大50文字）。\n",
        "tts join": "ボイスチャンネルに参加します。",
        "tts leave": "ボイスチャンネルから切断します。",
        "tts speed": "速さを指定します。（プレミアム限定）\n速さ: 設定したい速さ（数値-%、50～400）",
        "tts voice": "声の種類を指定します。（プレミアム限定）\n種類: 設定したい声の種類（A~H）",
        "tts dicts": "カスタム辞書関連のコマンドです。",
        "tts dicts add": "カスタム辞書に単語を登録します。\n置換元: 置き換え元（文字列）\n置換先: 置き換え先（文字列）",
        "tts dicts remove": "カスタム辞書から単語を消去します。\nターゲット: 消去したい単語の置換元/ID（文字列）",
        "tts dicts list": "カスタム辞書の一覧を表示します。",
        "tos": "利用規約を表示します。",
        "help": "ヘルプを表示します。\nコマンド名: 詳細を取得したいコマンドの名前（文字列、省略で標準のヘルプ）",
        "about": "SevenBotの情報を表示します。",
        "ping": "SevenBotのpingを測定します。",
        "search_command": "コマンドを検索します。\nテキスト: 検索するテキスト（文字列）",
        "shorten": "URLを短縮します。\nURL: 短縮するURL\n短縮ID: `https://7bot.ml/`の後の文字列（文字列、省略でランダム）",
        "getid": "ユーザーのIDを表示します。\nユーザー名: 指定した場合、ユーザー名で検索します。（文字列、省略で自分）",
        "level": "現在のレベルを取得します。\nターゲット: レベルを取得するメンバー（ユーザー、省略で自分）",
        "lookup": "ターゲットの情報を取得します。\nターゲット: 情報を取得するユーザー（ユーザー、省略で自分）",
        "vote": "投票を作成します。\nタイトル: 投票のタイトル（文字列）\n長さ: 票を受け付ける日時（日時）\n複数投票: 複数投票を許容するか（Y/N）\n選択肢: 選択肢（リスト-文字列、最大10個）",
        "party": "先着順の募集を作成します。\nタイトル: 募集のタイトル（文字列）\n長さ: 参加を受け付ける日時（日時）\n最大人数: 最大人数（数値）",
        "translate": "Googletrans APIを使ってGoogle翻訳をします。\nテキスト: 翻訳するテキスト（文字列）",
        "check_url": "URLをNorton Safewebを使って安全か確かめます。\nURL: 安全か確かめたいURL（文字列）",
        "get_permissions": "ターゲットの権限を取得します。\nターゲット: 権限を取得したいロール・メンバー（ロール/メンバー、省略で自分）\nチャンネル: 権限を取得したいチャンネル（チャンネル、省略でサーバー権限）",
        "get_role_count": "全てのロールとロールがついている人数を取得します。\nBot表示: Bot専用のロールを表示するか（Y/N、省略でFalse）",
        "music": """音楽再生関連のコマンドです。""",
        "music join": "入力した人がいるボイスチャンネルに参加します。",
        "music play": "曲を再生します。\nURL: 再生したい曲のURL（文字列）",
        "music search_play": "検索した中から再生します。\n内容: 検索内容（文字列）",
        "music fast_play": "YouTubeで検索し、一番上に出てきたものを再生します。\n内容: 検索内容（文字列）",
        "music favorite": "お気に入りから曲を再生します。",
        "music leave": "ボイスチャンネルから退出します。",
        "music queue": "キューを表示します。\n履歴: 履歴を表示するか（Y/N、省略でN）",
        "music now": "現在の曲の情報を表示します。",
        "music volume": "音量を変更します。\n音量: 設定したい音量（数値-%、0～200、省略で音量表示）",
        "music loop": "ループを切り換えます。",
        "music skip": "現在の曲をスキップします。",
        "music stop": "停止します。",
        "music pause": "一時停止/再開します。",
        "music delete": "キューから曲を削除します。\n番号: 削除したい曲の番号（数値）",
        "autoreply": """自動返信関連のコマンドです。""",
        "autoreply add": "自動返信リストに追加します。\n条件: 返信する条件（文字列）\n返信: 返信するテキスト（文字列）\n" + """
条件・返信を!から始めると追加の効果があります。
**条件コマンド:**
`re` - 正規表現でマッチ
**返信コマンド:**
`noreply` - Discordの返信を使わない""",
        "autoreply remove": "自動返信リストから消去します。\n返信: 消去したい自動返信が返信するテキスト（文字列）",
        "autoreply list": "自動返信リストを全表示します。",
        "mute": "メンバーをミュートします。\nターゲット: ミュートしたいメンバー（メンバー）\n長さ: ミュートする日時（日時、省略で60分）",
        "event_channel": "イベントメッセージチャンネルを設定します。",
        "event_send": f"""イベントメッセージを設定します。
イベント名: 送信するイベント名（イベント名）
メッセージ: 送信するメッセージ（文字列）
**イベント名:**
{en}
メッセージ: 送信するメッセージ
**置き換え一覧:**
`!name`: 参加したメンバーの名前
`!mention`: 参加したメンバーのメンション
`!count`: 現在のメンバー数
`\\n`: 改行""",
        "free_channel": "フリーチャンネル作成パネルを送信します。",
        "tree": "サーバーのチャンネルをツリー状に表示します。",
        "server_stat": """サーバー統計チャンネル関連のコマンドです。""",
        "server_stat activate": f"サーバー統計チャンネルを有効にします。\n統計名: 有効化する統計の名前（リスト-文字列）\n統計リスト:\n```\n{st}```",
        "server_stat deactivate": "サーバー統計チャンネルを無効にします。\nチャンネル、カテゴリーは消去されます。",
        "invite": "招待URLを表示します。",
        "sudden_death": "突然の死を生成します。\nテキスト: 中央のテキスト（文字列）",
        "warn": "特定ユーザーをWarnします。\nターゲット: Warn対象（メンバー）\n回数: Warn回数（数値、省略で1回）",
        "warn_settings": """Warnの処罰関連のコマンドです。""",
        "warn_settings add": "Warnの処罰リストに追加します。\n回数: Warn回数（数字）\n処罰: 処罰内容（処罰ID）\n" + """
**処罰ID:**
`mute` - ミュート（日時）
`role_add` - ロール追加（ロール）
`role_remove` - ロール剥奪（ロール）
`kick` - キック（なし）
`ban` - BAN（なし）
設定: 処罰の設定""",
        "warn_settings remove": "Warnの処罰リストから消去します。\n返信: 消去したい自動返信が返信するテキスト（文字列）",
        "warn_settings list": "Warnの処罰リストを全表示します。",
        "bump": """Bump通知関連のコマンドです。""",
        "bump activate": "Bump通知を有効にします。",
        "bump deactivate": "Bump通知を無効にします。",
        "bump role": "Bump通知にメンションするロールを変更します。\nロール: メンションするロール（ロール、省略でオフ）",
        "dissoku": """ディス速のアップ通知関連のコマンドです。""",
        "dissoku activate": "ディス速のアップ通知を有効にします。",
        "dissoku deactivate": "ディス速のアップ通知を無効にします。",
        "dissoku role": "ディス速のアップ通知にメンションするロールを変更します。\nロール: メンションするロール（ロール、省略でオフ）",
        "channel_settings": """チャンネルの設定を変更します。""",
        "channel_settings slowmode": "低速モードを設定します。\n秒数: 低速モードの秒数（数値）",
        "channel_settings translate": """自動翻訳についての設定です。""",
        "channel_settings translate activate": "自動翻訳を有効にします。\n言語コード: ```\nja:日本語\nen:英語```\nその他:[Wikipedia(639-1)](http://ja.wikipedia.org/wiki/ISO_639-1%E3%82%B3%E3%83%BC%E3%83%89%E4%B8%80%E8%A6%A7)",
        "channel_settings translate deactivate": "自動翻訳を無効にします。",
        "channel_settings commands": """実行したチャンネルでのコマンドについての設定です。""",
        "expand_message": """メッセージリンク展開についての設定です。""",
        "expand_message activate": "メッセージリンク展開を有効にします。",
        "expand_message deactivate": "メッセージリンク展開を無効にします。",
        "channel_settings commands activate": "実行したチャンネルでのコマンドを有効にします。",
        "channel_settings commands deactivate": "実行したチャンネルでのコマンドを無効にします。\n実行後は`チャンネルの管理`権限がないとコマンドを実行できないようになります。",
        "channel_settings 2ch_link": """2ch風メッセージリンクについての設定です。""",
        "channel_settings 2ch_link activate": "2ch風メッセージリンクを有効にします。",
        "channel_settings 2ch_link deactivate": "2ch風メッセージリンクを無効にします。",
        "channel_settings level": """レベリングについての設定です。""",
        "channel_settings level activate": "レベリングを有効にします。",
        "channel_settings level deactivate": "レベリングを無効にします。",
        "channel_settings auto_publish": """自動公開についての設定です。""",
        "channel_settings auto_publish activate": "自動公開を有効にします。",
        "channel_settings auto_publish deactivate": "自動公開を無効にします。",
        "channel_settings auto_parse": """自動パースについての設定です。""",
        "channel_settings auto_parse activate": "自動パースを有効にします。",
        "channel_settings auto_parse deactivate": "自動パースを無効にします。",
        "channel_settings lainan_talk": """[Lainan API](https://lainan.one/)の返信についての設定です。""",
        "channel_settings lainan_talk activate": "[Lainan API](https://lainan.one/)の返信を有効にします。",
        "channel_settings lainan_talk deactivate": "[Lainan API](https://lainan.one/)の返信を無効にします。",
        "lainan_talk": "[Lainan API](https://lainan.one/) を使って会話します\n文章: 会話する文章（文字列）",
        "level_settings": """レベルシステムの設定コマンドです。""",
        "role_link": """ロールリンク関連のコマンドです。""",
        "role_link add": "ロールリンクを追加します。\nロール: このサーバーのリンクしたいロール（ロール）\nサーバー: リンクしたいサーバー（ID-サーバー）\nロール2: 他サーバーのリンクしたいロール（ID-ロール）",
        "role_link remove": "ロールリンクを削除します。\nロール: このサーバーの削除したいリンクロールのロール（ロール）\nロール2: 他サーバーの削除したいリンクロールのロール（ID-ロール）",
        "role_link list": "ロールリンクのリストを表示します。",
        "level_settings roles": """報酬ロールを管理します。""",
        "level_settings roles add": "報酬ロールを設定します。\nレベル: 報酬ロールを与えるレベル\nロール: 与えるロール",
        "level_settings roles remove": "報酬ロールを削除します。\nレベル: 削除したい報酬ロールが与えられるレベル",
        "level_settings roles list": "報酬ロールのリストを表示します。",
        "level_settings boost": """レベルブーストを管理します。""",
        "level_settings boost add": "レベルブーストを設定します。\nロール: レベルブーストを設定する対象（ロール/メンバー）\n倍率: レベルブーストの倍率（小数）",
        "level_settings boost remove": "レベルブーストを削除します。\nロール: 削除したいレベルブーストが設定されているロール",
        "level_settings boost list": "レベルブーストのリストを表示します。",
        "level_settings activate": "レベルシステムを有効にします。",
        "level_settings deactivate": "レベルシステムを無効にします。",
        "level_settings channel": "レベルアップ時のお知らせチャンネルを変更します。\nターゲット: レベルアップお知らせチャンネルの変更先（チャンネル、省略でリセット）",
        "level_settings manage": """メンバーのレベルを管理します。""",
        "level_settings manage add": "特定のメンバーにXPを与えます。\nターゲット: XPを与えるメンバー（メンバー）\nXP: 与えるXP（数値）",
        "level_settings manage remove": "特定のメンバーからXPを剥奪します。\nターゲット: XPを剥奪するメンバー（メンバー）\nXP: 剥奪するXP（数値）",
        "level_settings manage reset": "全員のレベルをリセットします。",
        "archive": "チャンネルをアーカイブします。",
        "gchat": """グローバルチャット関連のコマンドです。""",
        "gchat activate": "入力したチャンネルをグローバルチャットにします。\nチャンネル名: 参加したいチャンネル名（文字列、省略でデフォルトのグローバルチャット）",
        "gchat deactivate": "入力したチャンネルのグローバルチャットを解除します。",
        "gchat change_pass": "個人グローバルのパスワードを変更します。\nチャンネル名: パスワードを変更したい個人グローバルの名前（文字列）",
        "reencode": "入力したテキストを文字化けさせます。テキスト: 文字化けさせるテキスト（文字列）",
        "fatal": """実行注意！""",
        "fatal nick": """ニックネーム関係です。""",
        "fatal nick import": "エクスポートしたニックネームファイルを読み込みます。\n**`fatal nick import`でエクスポートしたファイルを添付してください。**",
        "fatal nick export": "ニックネームをエクスポートします。",
        "fatal nick shuffle": "ニックネームをシャッフルします。\n**`fatal nick export`を事前に実行しておくことを__強く__お勧めします。**",
        "fatal nick reset": "ニックネームをリセットします。",
        "fatal role": "ロール関係です。",
        "fatal role add": "一括でロールを追加します。\nロール: 追加するロール\nターゲット: ロールを追加する対象（ロール、省略でeveryone）",
        "fatal role remove": "一括でロールを削除します。\nロール: 削除するロール\nターゲット: ロールを削除する対象（ロール、省略でeveryone）",
        "fatal role kick": "ロールを持っている人を一括でキックします。\nロール: キックする対象（ロール）\n理由: キック理由（文字列）",
        "fatal role dm": "ロールを持っている人に一括でDMを送信します。\nロール: DMを送信する対象（ロール）\nメッセージ: メッセージ内容（文字列）",
        "emoji_list": "サーバーの絵文字を表示し、リアクションします。",
        "loop_trans": "メッセージを五カ国語で再翻訳します。\nテキスト: 翻訳するテキスト（文字列/メッセージURL）",
        "ticket": "チケット作成メッセージを送信します。\nタイトル: チケットのタイトル\n説明: チケットの説明",
        "serverinfo": "サーバーの情報を表示します。\nID: 表示するサーバーのID（ID-サーバー、省略で実行したサーバー）",
        "check_permissions": "SevenBotに必要な権限があるかチェックします。",
        "lockdown": "チャンネルを封鎖します。\n再実行で解放します。",
        "sevennet": """SevenNet関連のコマンドです。\nSevenNet: SevenBotのSNS風グローバルチャット。Twitter的な""",
        "sevennet activate": "入力したチャンネルをSevenNetチャンネルにします。",
        "sevennet deactivate": "入力したチャンネルのSevenNetチャンネルを解除します。",
        "parse": "入力したチャンネルのカッコ類がしっかり閉じられているか確認します。",
        "auth": "認証パネルを作成します。",
        "auth react": "リアクション認証を作成します。\nロール: 認証後に付与するロール（ロール、省略で変更なし。初回は省略不可）",
        "auth image": "画像認証を作成します。\nロール: 認証後に付与するロール（ロール、省略で変更なし。初回は省略不可）",
        "auth web": "Web認証を作成します。\nロール: 認証後に付与するロール（ロール、省略で変更なし。初回は省略不可）",
        "role": "ロールパネルを作成します。\n複数選択: 複数選択を許可するか（Y/N）\nロール: ロールのメンション（リスト-ロール、最大10個）",
        "ww_role": "人狼の生存/死亡ロールを設定します。\nロールタイプ: 設定するロールの種類（alive/dead）\nロール: 設定するロール（ロール、省略で未設定化）",
        "image 5000": "[5000choyen-api](https://github.com/CyberRex0/5000choyen-api)を使って5000兆円欲しい！を生成します。\n上部: 上に入るテキスト（文字列）\n下部: 下に入るテキスト（文字列）",
        "develop_tool chr_info": "文字の情報を表示します。\nテキスト: 情報を表示するテキスト",
        "develop_tool rtfm": "リファレンスを検索します。",
        "develop_tool rtfm dpy": "[discord.py](https://discordpy.readthedocs.io/ja/latest/)のリファレンスを検索します。\nキーワード: 検索するキーワード。",
        "develop_tool rtfm djs": "[discord.js](https://discord.js.org/#/docs/main)のリファレンスを検索します。\nキーワード: 検索するキーワード。",
        "snowflake": "Snowflake（DiscordのID）の情報を表示します。\nSnowflake: 情報を表示するSnowflake（数値）"
    },
    "help_categories": ["ヘルプ - カテゴリー一覧", "sb#help <カテゴリー名> でそのカテゴリーのコマンドを表示します。", "`{}`のコマンド一覧", "sb#help <コマンド名> でコマンドのヘルプを表示します。"],
    "help_ranking": "使用回数の多いコマンドTop10",
    "help_category_helps": {
        'uses': "使用回数の多いコマンドを10位までを表示します。",
        'bot': "Botの情報関連です。",
        'server': "サーバーの情報関連です。",
        'info': "その他情報です。",
        'panel': "パネルを作成します。",
        'tools': "色々なツールです。",
        'fun': "ネタコマンドです。",
        'serverpanel': "サーバー関連のパネルを作成します。",
        'moderation': "モデレーション関連です。",
        'global': "グローバルチャット関連です。",
        'settings': "色々な設定です。"},
    #         "helps"	: ["""
    # **help**
    # ヘルプを表示します。
    # **about**
    # Botについて表示します。
    # **getid**
    # ユーザーのIDを表示します。
    # **invite**
    #  招待URLを生成します。
    # **level**
    # 現在のレベルを取得します。
    # **lookup**
    # ターゲットの情報を取得します。
    # **afk**
    # AFKになります。
    # **tos**
    # 利用規約を送信します。
    # """,
    #                """**vote**
    # 投票を作成します。
    # **recruit**
    # 先着順の募集を作成します。
    # **translate**
    # Googletrans APIを使ってGoogle翻訳をします。
    # **check_url**
    # URLをNorton Safewebを使って安全か確かめます。
    # **music/**
    # 音楽再生関連のコマンドです。
    # """,
    #                """
    # **ping**
    # Pingを簡易的に測定します。
    # **get_permissions**
    # 権限を取得します。
    # **get_role_count**
    # 全てのロールとロールがついている人数を取得します。
    # **tree**
    # このサーバーのチャンネルを表示します。
    # """,
    #                """
    # **bignum**
    # ビッグナンバーをします。
    # ルールはプレイ時に送信されます。
    # **werewolf**
    # 人狼をします。
    # """,
    #                f"""__**以下、権限が必要**__
    # **autoreply/**
    # 自動返信関連のコマンドです。
    # **clear_channel**
    # 入力したテキストチャンネルの履歴を一括消去します。
    # **mute**
    # メンバーをミュートします。
    # **event_channel**
    # イベントメッセージチャンネルを設定します。
    # **event_send**
    # イベントメッセージを設定します。
    # **role_link/**
    # ロールリンク関連のコマンドです。
    # """,
    #                f"""
    # **server_stat/**
    # サーバー統計チャンネル関連のコマンドです。
    # **ticket**
    # チケット作成メッセージを送信します。
    # """,
    #                """
    # **channel_settings/**
    # チャンネル設定関連のコマンドです。
    # **bump/**
    # Bump通知関連のコマンドです。
    # **expand_message/**
    # メッセージリンク展開関連のコマンドです。
    # **level_settings/**
    # レベルシステムの設定コマンドです。
    # **gchat/**
    # グローバルチャット関連のコマンドです。
    # **sevennet/**
    # SevenNet関連のコマンドです。
    # """,
    #                """
    # **auth**
    # リアクション認証を作成します。
    # **role**
    # ロールパネルを作成します。
    # **fatal**
    # 実行注意！
    # """
    #                ],
    #     "help_first": """
    # `/`はサブコマンドあり
    # `sb#help <コマンド名>`でサブコマンド、引数を表示
    #  """,
    "page_footer": r"ページ (\d+)/\d+",
    "lang_name": {'en': '英語',
                  'is': 'アイスランド語',
                  'ay': 'アイマラ語',
                  'ga': 'アイルランド語',
                  'az': 'アゼルバイジェン語',
                  'as': 'アッサム語',
                  'aa': 'アファル語',
                  'ab': 'アプハジア語',
                  'af': 'アフリカーンス語',
                  'am': 'アムハラ語',
                  'ar': 'アラビア語',
                  'sq': 'アルバニア語',
                  'hy': 'アルメニア語',
                  'it': 'イタリア語',
                  'yi': 'イディッシュ語',
                  'iu': 'イヌクティトット語',
                  'ik': 'イヌピア語',
                  'ia': 'インターリングア',
                  'ie': 'インターリング語',
                  'in': 'インドネシア語',
                  'ug': 'ウイグル語',
                  'cy': 'ウェールズ語',
                  'vo': 'ヴォラピュック語',
                  'wo': 'ウォロフ語',
                  'uk': 'ウクライナ語',
                  'uz': 'ウズベク語',
                  'ur': 'ウルドゥー語',
                  'et': 'エストニア語',
                  'eo': 'エスペラント語',
                  'or': 'オーリア語',
                  'oc': 'オキタン語',
                  'nl': 'オランダ語',
                  'om': 'オロモ語',
                  'kk': 'カザフ語',
                  'ks': 'カシミール語',
                  'ca': 'カタラン語',
                  'gl': 'ガリシア語',
                  'ko': '韓国語',
                  'kn': 'カンナダ語',
                  'km': 'カンボジア語',
                  'rw': 'キヤーワンダ語',
                  'el': 'ギリシャ語',
                  'ky': 'キルギス語',
                  'rn': 'キルンディ語',
                  'gn': 'グアラニー語',
                  'qu': 'クエチュア語',
                  'gu': 'グジャラト語',
                  'kl': 'グリーンランド語',
                  'ku': 'クルド語',
                  'ckb': '中央クルド語',
                  'hr': 'クロアチア語',
                  'gd': 'ゲーリック語',
                  'gv': 'ゲーリック語',
                  'xh': 'コーサ語',
                  'co': 'コルシカ語',
                  'sm': 'サモア語',
                  'sg': 'サングホ語',
                  'sa': 'サンスクリット語',
                  'ss': 'シスワティ語',
                  'jv': 'ジャワ語',
                  'ka': 'ジョージア語',
                  'sn': 'ショナ語',
                  'sd': 'シンド語',
                  'si': 'シンハラ語',
                  'sv': 'スウェーデン語',
                  'su': 'スーダン語',
                  'zu': 'ズールー語',
                  'es': 'スペイン語',
                  'sk': 'スロヴァキア語',
                  'sl': 'スロヴェニア語',
                  'sw': 'スワヒリ語',
                  'tn': 'セツワナ語',
                  'st': 'セト語',
                  'sr': 'セルビア語',
                  'sh': 'セルボクロアチア語',
                  'so': 'ソマリ語',
                  'th': 'タイ語',
                  'tl': 'タガログ語',
                  'tg': 'タジク語',
                  'tt': 'タタール語',
                  'ta': 'タミル語',
                  'cs': 'チェコ語',
                  'ti': 'チグリニャ語',
                  'bo': 'チベット語',
                  'zh-CN': '中国語(簡体字)',
                  'zh-TW': '中国語(繁体字)',
                  'ts': 'ヅォンガ語',
                  'te': 'テルグ語',
                  'da': 'デンマーク 語',
                  'de': 'ドイツ語',
                  'tw': 'トウィ語',
                  'tk': 'トルクメン語',
                  'tr': 'トルコ語',
                  'to': 'トンガ語',
                  'na': 'ナウル語',
                  'ja': '日本語',
                  'ne': 'ネパール語',
                  'no': 'ノルウェー語',
                  'ht': 'ハイチ語',
                  'ha': 'ハウサ語',
                  'be': '白ロシア語',
                  'ba': 'バシキール語',
                  'ps': 'パシト語',
                  'eu': 'バスク語',
                  'hu': 'ハンガリー語',
                  'pa': 'パンジャビ語',
                  'bi': 'ビスラマ語',
                  'bh': 'ビハール語',
                  'my': 'ビルマ語',
                  'hi': 'ヒンディー語',
                  'fj': 'フィジー語',
                  'fi': 'フィンランド語',
                  'dz': 'ブータン語',
                  'fo': 'フェロー語',
                  'fr': 'フランス語',
                  'fy': 'フリジア語',
                  'bg': 'ブルガリア語',
                  'br': 'ブルターニュ語',
                  'vi': 'ベトナム語',
                  'iw': 'ヘブライ語',
                  'fa': 'ペルシャ語',
                  'bn': 'ベンガル語',
                  'pl': 'ポーランド語',
                  'pt': 'ポルトガル語',
                  'mi': 'マオリ語',
                  'mk': 'マカドニア語',
                  'mg': 'マダガスカル語',
                  'mr': 'マラッタ語',
                  'ml': 'マラヤーラム語',
                  'mt': 'マルタ語',
                  'ms': 'マレー語',
                  'mo': 'モルダビア語',
                  'mn': 'モンゴル語',
                  'yo': 'ヨルバ語',
                  'lo': 'ラオタ語',
                  'la': 'ラテン語',
                  'lv': 'ラトビア語',
                  'lt': 'リトアニア語',
                  'ln': 'リンガラ語',
                  'li': 'リンブルク語',
                  'ro': 'ルーマニア語',
                  'rm': 'レートロマンス語',
                  'ru': 'ロシア語'},
    "permissions_text": [
        {"name": "サーバー全般の権限",
         "administrator": "管理者",
         "view_audit_log": "監査ログを表示",
         "manage_guild": "サーバー管理",
         "manage_roles": "ロールの管理",
         "manage_channels": "チャンネルの管理",
         "kick_members": "メンバーをキック",
         "ban_members": "メンバーをBAN",
         "create_instant_invite": "招待を作成",
         "change_nickname": "ニックネームの変更",
         "manage_nicknames": "ニックネームの管理",
         "manage_emojis": "絵文字の管理",
         "manage_webhooks": "ウェブフックの管理",
         "view_guild_insights": "テキストチャンネルの閲覧＆ボイスチャンネルの表示",
         },
        {"name": "テキストの権限",
         "view_guild_insights|read_messages": "メッセージを読む",
         "send_messages": "メッセージを送信",
         "send_tts_messages": "TTSメッセージを送信",
         "manage_messages": "メッセージの管理",
         "embed_links": "埋め込みリンク",
         "attach_files": "ファイルを添付",
         "read_message_history": "メッセージ履歴を読む",
         "mention_everyone": "@everyone、@here、全てのロールにメンション",
         "external_emojis": "外部の絵文字の使用",
         "add_reactions": "リアクションの追加",
         "use_slash_commands": "スラッシュコマンドの使用",
         },
        {
            "name": "音声の権限",
            "connect": "接続",
            "speak": "発言",
            "stream": "動画",
            "mute_members": "メンバーをミュート",
            "deafen_members": "メンバーのスピーカーをミュート",
            "move_members": "メンバーを移動",
            "use_voice_activation": "音声検出を使用",
            "priority_speaker": "優先スピーカー",
            "request_to_speak": "発言を申請"
        }
    ],
    "only_admin": "このコマンドはBotオーナーにしか実行できません。",
    "missing_permissions": [
        "権限がありません。",
        "このコマンドを実行するには以下の権限が必要です："
    ],
    "role_link": {
        "add": "ロールリンクに`@{}`を追加しました。",
        "add_desc": "`{0}`の{1}は`{2}`の`{3}`とリンクします。",
        "remove": "`@{}`のロールリンクを削除しました。",
        "remove_fail": "ロールリンクは見付かりませんでした。",
        "list": "ロールリンク一覧",
        "no_role_perm": "リンク先での権限がありません。",
        "not_in_server": "リンク先のサーバーに入っていません。",
        "unknown_server": "不明なサーバーです。",
        "unknown_role": "不明なロールです。",
        "reason": "ロールリンク（{}の@{}）",
        "update": "ロールリンクをアップデートしました。"
    },
    "tips_title": "Tips",
    "tips": {
        "help_alias": """
ヘルプコマンド（`sb#help`）は`sb#h`でも呼び出せます。
結構楽だよ。
""",
        "default_global": """
個人グローバルチャットは公式で何個か用意してるよ。
公式サーバーをチェック！（`sb#about`）
""",
        "tips_arg": """
Tipsコマンドには引数を設定出来るよ。
フッターに出てくるID（これは`tips_arg`）を入力すれば好きなTipsを表示できるよ。
""",
        "topgg": """
[ここ](https://top.gg/bot/718760319207473152)でUpvote（高評価）すると開発モチベが上がるよ。
やってね（）
""",
        "premium": """
SevenBot公式サーバーをブーストするとSevenBot Premiumが使えるよ！
ブーストしてね！
"""


    }



}
