
Event_dict2 = {
    "join": "On join",
    "leave": "On leave"
}
Stat_dict2 = {
    "members": "Members",
    "humans": "Users",
    "bots": "Bots",
    "onlines": "Onlines",
    "online_per": "Online percent",
    "channels": "Channels",
    "text_channels": "Text channels",
    "voice_channels": "Voice channels",
    "roles": "Roles"
}
en2 = ""
for ek, ev in Event_dict2.items():
    en2 += f"`{ek}`: {ev}\n"
st2 = ""
for ek, ev in Stat_dict2.items():
    st2 += f"`{ek}`: {ev}\n"
EN_TEXTS = {"help_title": "SevenBot help",
            "help_closed": "{} to reopen the help",
            "expand_message_fail": "Failed to get message.",
            "expand_message_footer": "Channel: {}",
            "expand_message_footer2": "Channel: {}, {} embed(s).",
            "message_delete": "This message will be deleted in {} second(s).",
            "page": "Page",
            "get_rm": "Member of role `@{}`",
            "timeout": "Timeout.",
            "translate_title": "Translate({} to {})",
            "yt_played": " will play soon.",
            "yt_queued": " has been added to queue.",
            "yt_queued_footer": "Queue has {} song(s) now.",
            "yt_queue_end": "Queue has ended.",
            "yt_queue_list": "Current queue",
            "yt_queue_empty": "The queue is Empty.",
            "yt_premium": "You have SevenBot Premium!",
            "yt_premium_desc": "The music will play with 512 kbps.",
            "yt_not_connect": "I'm not in Voice channel.",
            "yt_not_connect3": "You're not in Voice channel.",
            "yt_not_connect2": "Please try again after connecting to the voice channel.",
            "yt_disconnect": "Disconnected from `{}`.",
            "yt_reconnect": "`sb#music join` to reconnect.",
            "bump_detected": "Bump detected.",
            "bump_detected_desc": "I'll send alert after 2 hours.\n"
            "`sb#bump deactivate` to deactivate.",
            "bump_alert": "It's time to Bump!",
            "bump_alert_desc": "`!d bump` to bump.",
            "bump_role_set": "I'll mention the role in bump alert.",
            "bump_role_set_none": "I won't mention in bump alert.",
            "dissoku_detected": "Up detected.",
            "dissoku_detected_desc": "I'll send alert after 1 hour.\n`sb#dissoku deactivate` to deactivate.",
            "dissoku_alert": "It's time to up!",
            "dissoku_alert_desc": "`/dissoku up!` to up.",
            "dissoku_role_set": "I'll mention the role in up alert.",
            "dissoku_role_set_none": "I won't mention the role in bump alert.",
            "img_auth_header": "Image Authorization",
            "archive_title": "Archived this channel.",
            "archive_category": "Archived Channels",
            "img_auth_desc": "Please send the code.",
            "img_auth_warn": "It'll be timeouted in 30 seconds",
            "img_auth_ok": "Authorized",
            "dm_fail": "Couldn't send DM.",
            "color_names": ["Red", "Orange", "Lime", "Green", "Cyan", "Aqua", "Blue", "DarkBlue", "Purple", "Magenta"],
            "activate": "{} has been activated.",
            "activate_fail": "Already active.",
            "activate_desc": "`{}` to deactivate.",
            "deactivate": "{} has been deactivated.",
            "deactivate_fail": "Already disable.",
            "deactivate_desc": "`{}` to activate.",
            "voting": ["vote",
                          "Title",
                          "Multi-Voting",
                          ["Allow", "Deny"],
                          "Choices",
                          "Ends at:"],
            "vote_error": ["Too many choices.", "You can set 10 choices or less."],
            "getid_self": ["Your ID is `{}`.", "Use it freely."],
            "getid_search": ["List of member named `{}`",
                             "Perfect matches",
                             "Part matches",
                             "No matches"],
            "ping_title": "Ping test",
            "ping_desc": "My ping is `{}ms`.",
            "how_to_use": "Subcommands",
            "getting": "Now getting...",
            "favorite": "Favorites",
            "wait": "Please wait.",
            "command_search": "Command search.",
            "selected": "has selected.",
            "canceled": "Canceled.",
            "nico_failed": "Failed.",
            "nico_api_die": "API of niconico isn't working now.",
            "nico_wrong_query": "Try again with other query.",
            "yt_search_result": "Search result",
            "yt_no_matches": "No matches.",
            "yt_search_try_again": "Try again with other query.",
            "yt_no_fav": "You have no favorites.",
            "yt_no_fav_desc": "You can resister with {}.",
            "yt_play_wait": "Playing...",
            "yt_join_wait": "Connecting to `{}`...",
            "yt_join_done": "Connected to `{}`.",
            "yt_join_desc": "`sb#music` to show about playing commands.",
            "no_desc": "- No description -",
            "afk_title": "`{}` is now afk.",
            "afk_reason_none": "(No reason)",
            "afk_reason": "Reason:",
            "afk_register": "You're now AFK.",
            "afk_register_desc": "AFK will be lifted when you say something.",
            "afk_off": "You're no longer AFK.",
            "afk_off_desc": "You got mentioned {} time(s).",
            "afk_off_unknown": "(Unknown)",
            "yt_loop_activate": "Loop activated.",
            "yt_loop_deactivate": "Loop deactivated.",
            "yt_loop_activate_desc": "Will play first song when last song finished.",
            "yt_loop_deactivate_desc": "Won`t play first song when last song finished.",
            "yt_pause_activate": "Pauesed.",
            "yt_pause_deactivate": "Resumed.",
            "yt_pause_desc": "`sb#music pause` to switch pause.",
            "yt_stop": "Successfully stopped.",
            "yt_queue_del": "Song deleted.",
            "yt_queue_del_desc": "Queue has {} song(s) now.",
            "yt_queue_del_fail": "Failed to delete song.",
            "yt_queue_del_fail_desc": "Invaild index.",
            "yt_fail_get": "Failed to get information of song.",
            "yt_fail_get_desc": "Check your URL.",
            "yt_current_song": "Now playing",
            "yt_cu": "I'm not playing song now.",
            "yt_fav_add": "`{}` has been added to your favorite.",
            "yt_fav_del": "`{}` has been removed to your favorite.",
            "yt_fav_info": "Your favorite has {} song(s).",
            "yt_not_playing": "Song is not playing.",
            "yt_now_playing": ["Title", "Uploader", "URL", "Seek"],
            "yt_skip": "Skipped.",
            "no_role_perm": "You don't have permissions to give `@{}`.",
            "yt_queue_end_desc": "Resister with `sb#music play`(Etc).",
            "yt_footer": "Queue index:{}/{} Ext:{}",
            "unknown_cmd": "Unknown command.",
            "rc_title": "Roles and members",
            "rc_people": " member(s)",
            "see_help": "`sb#help` to see helps.",
            "bad_arg": "Bad argument.",
            "error": "An error occurred.",
            "permission_title": "{}`s permissions",
            "permission_value": "Value:",
            "ls": {"not_active": "Level system isn't active in this server",
                      "not_active_desc2": "Use it in server where level system is active.",
                      "not_active_desc": "Activate with `sb#level_settings activate`.",
                      "rank": ["No.", "Name", "Level", "XP"],
                      "rank_title": "Level ranking",
                      "manage": {"add": "{0} got {1}XP.",
                                 "remove": "{0} lost {1}XP.",
                                 "reset": "Levels have reseted."},
                      "roles": {"add": "A reward role has registered.",
                                "remove": "A reward role has removeed.",
                                "remove_fail": "Couldn't find reward role.",
                                "list": "List of reward role"}},
            "lockdown_title": "Locked this channel.",
            "lockdown_desc": "Removed `Send messages` permission from these roles.",
            "lockdown_footer": "Do not unpin this message.",
            "unlock_title": "Unlocked this channel.",
            "unlock_desc": "Added `Send messages` permission from these roles.",
            "norton_res": "This site is `{}`.",
            "norton_desc": [["Untested", "Norton didn't test the site."],
                            ["Safe",
                                "Norton Safe Web has analyzed {} for safety and security "
                                "problems. "],
                            ["Caution",
                                "Web sites rated \"Caution\" may have a small number of "
                                "threats and annoyances, but are not considered dangerous "
                                "enough to warrant a red \"Warning\". Proceed with caution."],
                            ["Warning",
                                "This is a known dangerous web page. It is highly "
                                "recommended that you do NOT visit this page."]],
            "trans_before": "Before",
            "trans_after": "After",
            "free_channel_title": "Free channel",
            "free_channel_desc": "Press {} to create channel.",
            "free_channel_ask": "Please input name of new channel.",
            "free_channel_success": "Created a new channel.",
            "free_channel_success_desc": "Move channel: {}",
            "free_channel_topic": "{}'s free channel.",
            "lookup": ["{}'s info",
                          "Server name",
                          "User name",
                          "Account created at:",
                          "Server joined at:",
                          ["Unknown",
                           "Online",
                           "Idle",
                           "Do not disturb",
                           "Offline",
                           "Status"],
                          "Roles",
                          "Not in this server.",
                          ["Yes", "No"]],
            "abouts": ["SevenBot's information",
                       "Developer",
                       "Language",
                       "Official server(You can request Global-Ban here)",
                       "Servers",
                       "Users",
                       "Global chats",
                       "SevenNet ",
                       "Upvotes in top.gg",
                       "{}(Monthly: {})\n"
                       "Upvote [here](https://top.gg/bot/718760319207473152)!",
                       "Coop Bot",
                       "Invite",
                       "Support Server",
                       "Special Thanks",
                       "[Discord Bot Portal JP](https://discord.gg/FWw6VqQ),[discord.py "
                       "Official](https://discord.gg/dpy), and server owner who invited "
                       "this bot.",
                       " Servers",
                       " People"],
            "tree": "Channels of this guild",
            "ch": {"slowmode": ["Slowmode is now `{}` second(s)."]},
            "big-number": {"title": "Big-Number",
                           "waiting": "Waiting for players.",
                           "waiting_desc": "To start game, needs `3` players.\n"
                           "{} to join(start),{} to leave(cancel).",
                           "players": "Players(Current: `{}`)",
                           "ready": "Ready",
                           "cancel": "Cancel",
                           "ready_desc": "Game starts with `{}` players.",
                           "input": "Input",
                           "input_desc": "Send number from 1 to 10.\n"
                           "The biggest person wins.\n"
                           "But if you overlap, you lose.\n"
                           "And 1 can win only 10.\n"
                           "Please send within 1 minute.",
                           "input2": "Receive",
                           "input2_desc": "Waiting for players' input.",
                           "input_received": "Input received",
                           "input_received2": "Received {}'s input",
                           "no_dm": "Couldn't send DM.",
                           "timeout": "Time out.",
                           "result": "Result",
                           "result_desc1": "{} won with `{}`!\n"
                           "Congratulations!\n"
                           "**Players' input:**\n",
                           "result_desc2": "Every player overapped!\n"
                           "Draw!\n"
                           "**Players' input:**\n",
                           "double": "(Overlapped)"},
            "prefix_changed": ["Prefix has changed `{}` to `{}`.",
                               "`{}change_prefix` to reset.",
                               "(Default)"],
            "parse": [["Goods brackets.", "Every `(`,`{`,`[` are closed."],
                      "Bad brackets.",
                      "{1} `{0}`s are open.",
                      "{1} `{0}`s are in invaild place.`{}` is open."],
            "change_lang": [["Couldn't change language.", "Unknown language({})."],
                            ["Language has successfully changed.", "SevenBot will use {}."]],
            "ww": {"title": "Werewolf",
                   "waiting": "Waiting for players.",
                   "waiting_desc": "To start game, needs `6` players.\n"
                   "{} to join(start),{} to leave(cancel).",
                   "players": "Players(Current: `{}`)",
                   "ready": "Ready",
                   "cancel": "Cancel",
                   "ready_desc": "Game starts with `{}` players.",
                   "your_role": "Your role is `{}`.",
                   "roles": [["Human", "No skills.", 0],
                             ["占い師", "Every night,can know the_人狼_か_人間_か知ることが出来ます。", 0],
                             ["霊媒師", "昨晩処刑された人が_人狼_か_人間_か知ることが出来ます。", 0],
                             ["狩人",
                                 "毎晩、誰か1人を選び、その人を_人狼_から守ることが出来ます。\nただし、昨晩守った人、自分は選ぶことができません。",
                                 0],
                             ["人狼", "毎晩、誰か1人を選び、その人を襲撃します。", 1]],
                   "win_cond": ["**勝利条件：**", "_人狼_を全員処刑する。", "人狼の数と人間の数が同数になる。"],
                   "team": ["人間", "人狼"],
                   "day": "`{}`日目",
                   "noon": "昼時間",
                   "noon_desc": "昼時間です。「誰が人狼か」を議論して下さい。\n"
                   "3分後に投票に入ります。\n"
                   "{}を全員が押すことでスキップできます。",
                   "vote": "投票時間",
                   "vote2": "投票",
                   "vote3": "再投票",
                   "vote_desc": "投票です。\n処刑する人の番号を送信して下さい。",
                   "vote_wait_desc": "プレイヤーの入力を待っています。",
                   "vote_received": "入力を受け付けました。",
                   "vote_received2": "{}の入力を受け付けました。",
                   "vote_draw": "同数票があったため、再投票を行います。",
                   "vote_draw2": "再投票しても同数票があったため、くじで__{}__が処刑されました。",
                   "vote_result": "処刑",
                   "vote_result_desc": "__{}__が処刑されました。",
                   "remain": "残り {} 人",
                   "night": "夜時間",
                   "night_desc": "夜時間です。",
                   "no_dm": "DMを送信できませんでした。",
                   "died": "襲撃",
                   "died_desc": "_人狼_の襲撃によって\n{}が死亡しました。",
                   "died_fail": "誰も死亡しませんでした。",
                   "dead": "(死亡)",
                   "result": "ゲーム終了",
                   "result_desc1": "村人陣営が勝利しました！\n**役職:**\n{}",
                   "result_desc2": "人狼陣営が勝利しました！\n**役職:**\n{}",
                   "night_txt": [["市民", "夜時間には何も出来ません。\nおやすみなさい。", 0],
                                 ["占い師",
                                     "1人選んでください。\nその人が_人狼_か_人間_か知ることが出来ます。",
                                     0,
                                     "__{}__は_{}_です。"],
                                 ["霊媒師", "1日目なので何も出来ません。", 0, "昨晩処刑された人は_{}_です。"],
                                 ["狩人", "1人選んでください。\nその人を_人狼_の襲撃から保護します。", 0],
                                 ["人狼", "1人選んでください。\nその人を襲撃します。", 1]]},
            "help_move": "移動したいページを送信してください。",
            "delta_txt": ["日", "時間", "分", "秒", "間"],
            "help_datail_aliases": "Aliases",
            "help_datail_subcommands": "Subcommands",
            "help_datail_aliases_none": "None",
            "help_datail_subcommands_none": "None",
            "help_none": "Couldn't find command.",
            "help_datail_none": "Couldn't find description.",
            "help_datail_syntax_name": "Syntax",
            "help_datail": {"afk": "Makes you be AFK.\nReason: Reason(String, Default:No reason)",
                            "level_ranking": "Shows ranking of level.",
                            "image": "Command about images.",
                            "image github": "Generate image like default icon of GitHub.\\Seed: Seed(String, Default:User ID)",
                            "tips": "Shows the tips of SevenBot.",
                            "tos": "Shows ToS.(Japanese)",
                            "help": "Shows help.\nCommand name: Command name what you want to see datail(String, Default:Category)",
                            "about": "Shows SevenBot's about",
                            "ping": "Shows SevenBot's ping,\nPing of between SevenBot and you.",
                            "search_command": "Searchs command.\nQuery: Query to search(String)",
                            "getid": "Shows User ID.\n"
                            "Name: User name who you want to see ID(String, Default:You)",
                            "level": "Gets level.\nTarget: Target(Member, Default:You)",
                            "lookup": "Gets target's info.\nTarget: 情報を取得するユーザー（ユーザー、省略で自分）",
                            "vote": "Makes vote.\n"
                            "Title: Title of the vote(String).\n"
                            "Length: Length of the vote(Time).\n"
                            "Multi-vote: Allow multi voting(Y/N)\n"
                            "Options: Options of the vote(List-String).",
                            "party": "Makes recruiting panel.\n"
                            "Title: Title of recruit(String).\n"
                            "Length: Length of recruit(Time).\n"
                            "Max: Max members of recruit(Integer).",
                            "translate": "Translate with aiogoogletrans.\n"
                            "Text: Text you want to translate(String).",
                            "check_url": "Checks the URL is safe or not.\n"
                            "URL: URL you want to check(String).",
                            "get_permissions": "Gets the permissions of target.\n"
                            "Target: Member you want to see get permissions(Member, Default:You)."
                            "Channel: Channel you want to see get permissions(Member, Default:Server permissions).",
                            "get_role_count": "Gets the role of the server.\n"
                            "Managed: Show managed role or not(Y/N, Default:No).",
                            "music": "About music playing.",
                            "music join": "Joins voice channel.",
                            "music play": "Plays music.\nURL: URL you want to play(URL-YouTube)",
                            "music search_play": "Search YouTube and play.\nQuery: Search query(String).",
                            "music fast_play": "Search YouTube and play the first.\n"
                            "Query: Search query(String).",
                            "music favorite": "Plays music from your favorites.",
                            "music leave": "Disconnects from voice channel.",
                            "music queue": "Shows queue.\nHistory: Show history or not(Y/N, Default:No)",
                            "music now": "Shows currently playing music.",
                            "music loop": "Switchs loop.",
                            "music skip": "Skips the music.",
                            "music stop": "Stops the music.",
                            "music pause": "Pause/resume the music.",
                            "music delete": "Remove music from queue.\nIndex: Index of music(Integer)",
                            "autoreply": "About auto-reply.",
                            "autoreply add": "自動返信リストに追加します。\n"
                            "条件: 返信する条件（文字列）\n"
                            "返信: 返信するテキスト（文字列）",
                            "autoreply remove": "自動返信リストから消去します。\n"
                            "返信: 消去したい自動返信が返信するテキスト（文字列）",
                            "autoreply list": "自動返信リストを全表示します。",
                            "mute": "メンバーをミュートします。\n"
                            "ターゲット: ミュートしたいメンバー（メンバー）\n"
                            "長さ: ミュートする時間（時間、省略で60分）",
                            "event_channel": "イベントメッセージチャンネルを設定します。",
                            "event_send": "イベントメッセージを設定します。\n"
                            "イベント名: \n"
                            "1\n"
                            "メッセージ: 送信するメッセージ\n"
                            "置き換え一覧:\n"
                            "`!name`: 参加したメンバーの名前\n"
                            "`!mention`: 参加したメンバーのメンション\n"
                            "`!count`: 現在のメンバー数\n"
                            "`\\n`: 改行",
                            "free_channel": "フリーチャンネル作成パネルを送信します。",
                            "server_stat": "サーバー統計チャンネル関連のコマンドです。",
                            "server_stat activate": "サーバー統計チャンネルを有効にします。\n統計名:```\n1```",
                            "server_stat deactivate": "サーバー統計チャンネルを無効にします。\n"
                            "チャンネル、カテゴリーは消去されます。",
                            "invite": "招待URLを表示します。",
                            "bump": "Bump通知関連のコマンドです。",
                            "bump activate": "Bump通知を有効にします。",
                            "bump deactivate": "Bump通知を無効にします。",
                            "bump role": "Bump通知にメンションするロールを変更します。\n"
                            "ロール: メンションするロール（ロール、省略でオフ）",
                            "dissoku": "ディス速のアップ通知関連のコマンドです。",
                            "dissoku activate": "ディス速のアップ通知を有効にします。",
                            "dissoku deactivate": "ディス速のアップ通知を無効にします。",
                            "dissoku role": "ディス速のアップ通知にメンションするロールを変更します。\n"
                            "ロール: メンションするロール（ロール、省略でオフ）",
                            "channel_settings": "チャンネルの設定を変更します。",
                            "channel_settings slowmode": "低速モードを設定します。\n秒数: 低速モードの秒数（数値）",
                            "channel_settings translate": "自動翻訳についての設定です。",
                            "channel_settings translate activate": "自動翻訳を有効にします。\n"
                            "言語コード:```\n"
                            "ja: 日本語\n"
                            "en: 英語```\n"
                            "その他: "
                            "[Wikipedia(639-1)](http://ja.wikipedia.org/wiki/ISO_639-1%E3%82%B3%E3%83%BC%E3%83%89%E4%B8%80%E8%A6%A7)",
                            "channel_settings translate deactivate": "自動翻訳を無効にします。",
                            "channel_settings commands": "実行したチャンネルでのコマンドについての設定です。",
                            "expand_message": "メッセージリンク展開についての設定です。",
                            "expand_message activate": "メッセージリンク展開を有効にします。",
                            "expand_message deactivate": "メッセージリンク展開を無効にします。",
                            "channel_settings commands activate": "実行したチャンネルでのコマンドを有効にします。",
                            "channel_settings commands deactivate": "実行したチャンネルでのコマンドを無効にします。\n"
                            "実行後は`チャンネルの管理`権限がないとコマンドを実行できないようになります。",
                            "channel_settings 2ch_link": "2ch風メッセージリンクについての設定です。",
                            "channel_settings 2ch_link activate": "2ch風メッセージリンクを有効にします。",
                            "channel_settings 2ch_link deactivate": "2ch風メッセージリンクを無効にします。",
                            "channel_settings level": "レベリングについての設定です。",
                            "channel_settings level activate": "レベリングを有効にします。",
                            "channel_settings level deactivate": "レベリングを無効にします。",
                            "channel_settings auto_publish": "自動公開についての設定です。",
                            "channel_settings auto_publish activate": "自動公開を有効にします。",
                            "channel_settings auto_publish deactivate": "自動公開を無効にします。",
                            "level_settings": "レベルシステムの設定コマンドです。",
                            "role_link": "ロールリンク関連のコマンドです。",
                            "role_link add": "ロールリンクを追加します。\n"
                            "ロール: このサーバーのリンクしたいロール（ロール）\n"
                            "サーバー: リンクしたいサーバー（ID-サーバー）\n"
                            "ロール2: 他サーバーのリンクしたいロール（ID-ロール）",
                            "role_link remove": "ロールリンクを削除します。\n"
                            "ロール: このサーバーの削除したいリンクロールのロール（ロール）\n"
                            "ロール2: 他サーバーの削除したいリンクロールのロール（ID-ロール）",
                            "role_link list": "ロールリンクのリストを表示します。",
                            "level_settings roles": "報酬ロールを管理します。",
                            "level_settings roles add": "報酬ロールを設定します。\n"
                            "レベル: 報酬ロールを与えるレベル\n"
                            "ロール: 与えるロール",
                            "level_settings roles remove": "報酬ロールを削除します。\n"
                            "レベル: 削除したい報酬ロールが与えられるレベル",
                            "level_settings roles list": "報酬ロールのリストを表示します。",
                            "level_settings activate": "レベルシステムを有効にします。",
                            "level_settings deactivate": "レベルシステムを無効にします。",
                            "level_settings channel": "レベルアップ時のお知らせチャンネルを変更します。\n"
                            "ターゲット: "
                            "レベルアップお知らせチャンネルの変更先（チャンネル、省略でリセット）",
                            "level_settings manage": "メンバーのレベルを管理します。",
                            "level_settings manage add": "特定のメンバーにXPを与えます。\n"
                            "ターゲット: XPを与えるメンバー（メンバー）\n"
                            "XP: 与えるXP（数値）",
                            "level_settings manage remove": "特定のメンバーからXPを剥奪します。\n"
                            "ターゲット: XPを剥奪するメンバー（メンバー）\n"
                            "XP: 剥奪するXP（数値）",
                            "level_settings manage reset": "全員のレベルをリセットします。",
                            "archive": "チャンネルをアーカイブします。",
                            "gchat": "グローバルチャット関連のコマンドです。",
                            "gchat activate": "入力したチャンネルをグローバルチャットにします。\n"
                            "チャンネル名: "
                            "参加したいチャンネル名（文字列、省略でデフォルトのグローバルチャット）",
                            "gchat deactivate": "入力したチャンネルのグローバルチャットを解除します。",
                            "gchat change_pass": "個人グローバルのパスワードを変更します。\n"
                            "チャンネル名: パスワードを変更したい個人グローバルの名前（文字列）",
                            "fatal": "実行注意！",
                            "fatal nick": "ニックネーム関係です。",
                            "fatal nick import": "エクスポートしたニックネームファイルを読み込みます。\n"
                            "**`fatal nick "
                            "import`でエクスポートしたファイルを添付してください。**",
                            "fatal nick export": "ニックネームをエクスポートします。",
                            "fatal nick shuffle": "ニックネームをシャッフルします。\n"
                            "**`fatal nick "
                            "export`を事前に実行しておくことを__強く__お勧めします。**",
                            "fatal nick reset": "ニックネームをリセットします。",
                            "ticket": "チケット作成メッセージを送信します。\nタイトル: チケットのタイトル\n説明: チケットの説明",
                            "check_permissions": "SevenBotに必要な権限があるかチェックします。",
                            "lockdown": "チャンネルを封鎖します。\n再実行で解放します。",
                            "sevennet": "SevenNet関連のコマンドです。\n"
                            "SevenNet: SevenBotのSNS風グローバルチャット。Twitter的な",
                            "sevennet activate": "入力したチャンネルをSevenNetチャンネルにします。",
                            "sevennet deactivate": "入力したチャンネルのSevenNetチャンネルを解除します。",
                            "parse": "入力したチャンネルのカッコ類がしっかり閉じられているか確認します。",
                            "auth": "認証パネルを作成します。",
                            "auth react": "リアクション認証を作成します。\n"
                            "ロール: 付与するロール（ロール、省略で変更なし。初回は省略不可）。",
                            "auth image": "画像認証を作成します。\n"
                            "ロール: 付与するロール（ロール、省略で変更なし。初回は省略不可）。",
                            "role": "ロールパネルを作成します。\n"
                            "複数選択: 複数選択を許可するか（Y/N）\n"
                            "ロール: ロールのメンション（リスト-ロール、最大10個）"},
            "help_categories": ["Help category list",
                                "You can see command of category with `sb#help <Category name>`",
                                "Command of `{}`",
                                "You can see help of command with `sb#help <Command name>`"],
            "help_ranking": "Use count ranking",
            "help_category_helps": {"uses": "Shows use count ranking.",
                                    "botinfo": "About SevenBot.",
                                    "serverinfo": "About server info.",
                                    "otherinfo": "About other info.",
                                    "panel": "About panel making.",
                                    "tools": "About some tools.",
                                    "fun": "About funny commands.",
                                    "serverpanel": "Makes moderation panel.",
                                    "moderation": "About moderation.",
                                    "global": "About global chats.",
                                    "settings": "Some settings."},
            "page_footer": "Page (\\d+)/\\d+",
            "lang_name": {"ab": "Abkhaz",
                          "aa": "Afar",
                          "af": "Afrikaans",
                          "ak": "Akan",
                          "sq": "Albanian",
                          "am": "Amharic",
                          "ar": "Arabic",
                          "an": "Aragonese",
                          "hy": "Armenian",
                          "as": "Assamese",
                          "av": "Avaric",
                          "ae": "Avestan",
                          "ay": "Aymara",
                          "az": "Azerbaijani",
                          "bm": "Bambara",
                          "ba": "Bashkir",
                          "eu": "Basque",
                          "be": "Belarusian",
                          "bn": "Bengali",
                          "bh": "Bihari",
                          "bi": "Bislama",
                          "bs": "Bosnian",
                          "br": "Breton",
                          "bg": "Bulgarian",
                          "my": "Burmese",
                          "ca": "Catalan; Valencian",
                          "ch": "Chamorro",
                          "ce": "Chechen",
                          "ny": "Chichewa; Chewa; Nyanja",
                          "zh": "Chinese",
                          "cv": "Chuvash",
                          "kw": "Cornish",
                          "co": "Corsican",
                          "cr": "Cree",
                          "hr": "Croatian",
                          "cs": "Czech",
                          "da": "Danish",
                          "dv": "Divehi; Maldivian;",
                          "nl": "Dutch",
                          "dz": "Dzongkha",
                          "en": "English",
                          "eo": "Esperanto",
                          "et": "Estonian",
                          "ee": "Ewe",
                          "fo": "Faroese",
                          "fj": "Fijian",
                          "fi": "Finnish",
                          "fr": "French",
                          "ff": "Fula",
                          "gl": "Galician",
                          "ka": "Georgian",
                          "de": "German",
                          "el": "Greek, Modern",
                          "gn": "Guaraní",
                          "gu": "Gujarati",
                          "ht": "Haitian",
                          "ha": "Hausa",
                          "he": "Hebrew (modern)",
                          "hz": "Herero",
                          "hi": "Hindi",
                          "ho": "Hiri Motu",
                          "hu": "Hungarian",
                          "ia": "Interlingua",
                          "id": "Indonesian",
                          "ie": "Interlingue",
                          "ga": "Irish",
                          "ig": "Igbo",
                          "ik": "Inupiaq",
                          "io": "Ido",
                          "is": "Icelandic",
                          "it": "Italian",
                          "iu": "Inuktitut",
                          "ja": "Japanese",
                          "jv": "Javanese",
                          "kl": "Kalaallisut",
                          "kn": "Kannada",
                          "kr": "Kanuri",
                          "ks": "Kashmiri",
                          "kk": "Kazakh",
                          "km": "Khmer",
                          "ki": "Kikuyu, Gikuyu",
                          "rw": "Kinyarwanda",
                          "ky": "Kirghiz, Kyrgyz",
                          "kv": "Komi",
                          "kg": "Kongo",
                          "ko": "Korean",
                          "ku": "Kurdish",
                          "kj": "Kwanyama, Kuanyama",
                          "la": "Latin",
                          "lb": "Luxembourgish",
                          "lg": "Luganda",
                          "li": "Limburgish",
                          "ln": "Lingala",
                          "lo": "Lao",
                          "lt": "Lithuanian",
                          "lu": "Luba-Katanga",
                          "lv": "Latvian",
                          "gv": "Manx",
                          "mk": "Macedonian",
                          "mg": "Malagasy",
                          "ms": "Malay",
                          "ml": "Malayalam",
                          "mt": "Maltese",
                          "mi": "Māori",
                          "mr": "Marathi (Marāṭhī)",
                          "mh": "Marshallese",
                          "mn": "Mongolian",
                          "na": "Nauru",
                          "nv": "Navajo, Navaho",
                          "nb": "Norwegian Bokmål",
                          "nd": "North Ndebele",
                          "ne": "Nepali",
                          "ng": "Ndonga",
                          "nn": "Norwegian Nynorsk",
                          "no": "Norwegian",
                          "ii": "Nuosu",
                          "nr": "South Ndebele",
                          "oc": "Occitan",
                          "oj": "Ojibwe, Ojibwa",
                          "cu": "Old Church Slavonic",
                          "om": "Oromo",
                          "or": "Oriya",
                          "os": "Ossetian, Ossetic",
                          "pa": "Panjabi, Punjabi",
                          "pi": "Pāli",
                          "fa": "Persian",
                          "pl": "Polish",
                          "ps": "Pashto, Pushto",
                          "pt": "Portuguese",
                          "qu": "Quechua",
                          "rm": "Romansh",
                          "rn": "Kirundi",
                          "ro": "Romanian, Moldavan",
                          "ru": "Russian",
                          "sa": "Sanskrit (Saṁskṛta)",
                          "sc": "Sardinian",
                          "sd": "Sindhi",
                          "se": "Northern Sami",
                          "sm": "Samoan",
                          "sg": "Sango",
                          "sr": "Serbian",
                          "gd": "Scottish Gaelic",
                          "sn": "Shona",
                          "si": "Sinhala, Sinhalese",
                          "sk": "Slovak",
                          "sl": "Slovene",
                          "so": "Somali",
                          "st": "Southern Sotho",
                          "es": "Spanish; Castilian",
                          "su": "Sundanese",
                          "sw": "Swahili",
                          "ss": "Swati",
                          "sv": "Swedish",
                          "ta": "Tamil",
                          "te": "Telugu",
                          "tg": "Tajik",
                          "th": "Thai",
                          "ti": "Tigrinya",
                          "bo": "Tibetan",
                          "tk": "Turkmen",
                          "tl": "Tagalog",
                          "tn": "Tswana",
                          "to": "Tonga",
                          "tr": "Turkish",
                          "ts": "Tsonga",
                          "tt": "Tatar",
                          "tw": "Twi",
                          "ty": "Tahitian",
                          "ug": "Uighur, Uyghur",
                          "uk": "Ukrainian",
                          "ur": "Urdu",
                          "uz": "Uzbek",
                          "ve": "Venda",
                          "vi": "Vietnamese",
                          "vo": "Volapük",
                          "wa": "Walloon",
                          "cy": "Welsh",
                          "wo": "Wolof",
                          "fy": "Western Frisian",
                          "xh": "Xhosa",
                          "yi": "Yiddish",
                          "yo": "Yoruba",
                          "za": "Zhuang, Chuang",
                          "zu": "Zulu"},
            "permissions_text": {"administrator": "Administrator",
                                 "view_audit_log": "View Audit Log",
                                 "manage_guild": "Manage Server",
                                 "manage_roles": "Manage Roles",
                                 "manage_channels": "Manage Channels",
                                 "kick_members": "Kick Members",
                                 "ban_members": "BAN Members",
                                 "create_instant_invite": "Create Instant Invite",
                                 "change_nickname": "Change Nickname",
                                 "manage_nicknames": "Manage Nicknames",
                                 "manage_emojis": "Manage Emojis",
                                 "manage_webhooks": "Manage Webhooks",
                                 "view_guild_insights": "View Channels",
                                 "send_messages": "Send Messages",
                                 "send_tts_messages": "Send TTS Messages",
                                 "manage_messages": "Manage Messages",
                                 "embed_links": "Embed links",
                                 "attach_files": "Attach Files",
                                 "read_message_history": "Read Messages",
                                 "mention_everyone": "Mention @everyone",
                                 "external_emojis": "Use External Emojis",
                                 "add_reactions": "Add Reactions",
                                 "connect": "Connect",
                                 "speak": "Speak",
                                 "stream": "Stream",
                                 "mute_members": "Mute Members",
                                 "deafen_members": "Deafen Members",
                                 "move_members": "Move Members",
                                 "use_voice_activation": "Use Voice Activity",
                                 "priority_speaker": "Priority Speaker"},
            "only_admin": "You can't run this command.",
            "missing_permissions": ["権限がありません。", "このコマンドを実行するには以下の権限が必要です："],
            "role_link": {"add": "ロールリンクに`@{}`を追加しました。",
                          "add_desc": "`{0}`の{1}は`{2}`の`{3}`とリンクします。",
                          "remove": "`@{}`のロールリンクを削除しました。",
                          "remove_fail": "ロールリンクは見付かりませんでした。",
                          "list": "ロールリンク一覧",
                          "no_role_perm": "リンク先での権限がありません。",
                          "not_in_server": "You're not in the server.",
                          "unknown_server": "Unknowns server.",
                          "unknown_role": "Unknown role.",
                          "reason": "Role-link(@{1} in {0})",
                          "update": "Role-link has been updated."},
            "tips_title": "Tips",
            "tips": {"help_alias": "\nYou can call `sb#help` with `sb#h`\nIt helps you a lot.",
                     "topgg": "\n"
                     "If you vote [here](https://top.gg/bot/718760319207473152), I'll make more features :)\n"
                     }
            }
